[project]
name = "hayalab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "hayato-n8810", email = "s276185@wakayama-u.ac.jp" }
]
requires-python = ">=3.13"
dependencies = [
    "apted>=1.0.3",
    "matplotlib>=3.10.8",
    "numpy>=2.4.0",
    "plotly>=6.7.0",
    "pydantic>=2.12.5",
    "pyyaml>=6.0.3",
    "scipy>=1.15.1",
    "tqdm>=4.67.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "ruff>=0.14.8",
]

[tool.ruff]
line-length = 200

[tool.ruff.format]
docstring-code-format = true
quote-style = "double"
exclude = ["**/__init__.py"]

[tool.ruff.lint]
select = [
    "F", # pyflakes
    "E", # pycodestyle
    "W", # pycodestyle warnings
    "I", # isort
    "D", # pydocstyle
    "N", # pep8-naming
]
exclude = ["**/__init__.py"]
ignore = [
    "D100", # undocumented-public-module
    "D107", # undocumented-public-init
    "D205", # blank-line-after-summary
    "D415", # ends-in-punctuation
    "E501", # Line too long
    "F403", # unable to detect undefined names
    "F405"  # undefined, or defined from star imports
]

[tool.ruff.lint.pydocstyle]
# docstringはgoogle style
convention = "google"
